import type { Decision, DecisionOption } from './schema';

// Farmz3D product pricing. Market prices: US Etsy/Amazon listings observed Sept 2026
// (Etsy read via search snippets; many are "sale" prices). Material cost = estimated grams
// of PLA x $0.016/g (Bambu Lab PLA Basic $15.99/kg); grams are estimates — weigh the first print.

const PLA_SOURCE = 'https://us.store.bambulab.com/products/pla-basic-filament';
const ETSY = 'https://www.etsy.com';

function plaCost(grams: number, extraCents = 0) {
  return Math.round(grams * 1.6) + extraCents;
}

function price(
  productId: string,
  title: string,
  unitLabel: string,
  grams: number,
  options: DecisionOption[],
  recommendedOptionId: string,
  evidence: Decision['evidence'],
  extraCostCents = 0,
  extraCostLabel?: string,
): Decision {
  return {
    id: `price:${productId}`,
    group: 'farmz3d-pricing',
    title,
    question: `Preço de venda (${unitLabel}).`,
    owner: 'bruna',
    unit: 'usd_cents',
    unitCostCents: plaCost(grams, extraCostCents),
    options,
    recommendedOptionId,
    evidence: [
      ...evidence,
      {
        label: `Material: ~${grams} g PLA${extraCostLabel ? ` + ${extraCostLabel}` : ''} (estimativa — pesar)`,
        value: `$${(plaCost(grams, extraCostCents) / 100).toFixed(2)}`,
        sourceUrl: PLA_SOURCE,
      },
    ],
  };
}

export const PRODUCT_DECISIONS: Decision[] = [
  price(
    'halloween-bucket-tag',
    'Trick-or-Treat Name Tag',
    'cada',
    10,
    [
      { id: 'low', label: 'Abaixo do mercado', value: 900, rationale: 'Menor preço observado (~$9). Produto de entrada para atrair pedidos.' },
      { id: 'market', label: 'Preço de mercado', value: 1200, rationale: 'Típico observado ($12–$12.50). Peça barata de imprimir.' },
      { id: 'premium', label: 'Premium', value: 1400, rationale: 'Acima do observado. Só com multicor/glitter.' },
    ],
    'market',
    [
      { label: 'Pumpkin boo basket tag', value: '$12.50', sourceUrl: `${ETSY}/listing/4360746971/pumpkin-boo-basket-name-tag-personalized` },
      { label: 'Trick or treat bucket tags', value: '$12.00', sourceUrl: `${ETSY}/listing/4352061848/custom-halloween-ghost-treat-bag-tags` },
      { label: '3D printed boo basket tag (snippet incerto)', value: '~$9.50', sourceUrl: `${ETSY}/listing/1782968131/personalized-kids-halloween-name-tag-3d` },
    ],
  ),
  price(
    'halloween-cookie-cutters',
    'Halloween Cookie Cutter Set (3 + cortador com nome)',
    'conjunto de 3 + 1 com nome',
    60,
    [
      { id: 'low', label: 'Soma dos mínimos', value: 1700, rationale: 'Conjunto de 3 ($11) + cortador com nome (~$6.50).' },
      { id: 'market', label: 'Preço de mercado', value: 2100, rationale: 'Conjunto típico ($13–$15) + cortador com nome típico ($6.50–$10).' },
      { id: 'high', label: 'Alto', value: 2500, rationale: 'Topo do mercado; difícil competir com conjuntos de $11.' },
    ],
    'market',
    [
      { label: 'Conjunto de 3 (vários vendedores)', value: '$11.00–$11.35', sourceUrl: `${ETSY}/listing/1054109011/halloween-cookie-cutter-set-3d-printed` },
      { label: 'Ghost trio / Boo 3 peças', value: '$14.70–$14.78', sourceUrl: `${ETSY}/listing/1757513592/ghost-trio-cookie-cutter-set-halloween` },
      { label: 'Conjunto vampiro (topo)', value: '$16.68', sourceUrl: `${ETSY}/listing/4347974679/vampire-halloween-cutter-set-platter` },
      { label: 'Cortador com nome da família', value: '$3.99–$15 (típico $6.50–$10)', sourceUrl: `${ETSY}/market/custom_cookie_stencils` },
    ],
  ),
  price(
    'halloween-lithophane',
    'Spooky Photo Lithophane Light',
    'cada',
    60,
    [
      { id: 'nightlight', label: 'Versão luz de tomada', value: 1900, rationale: 'Plug-in night lights ficam em $8–$15. Só vale sem base.' },
      { id: 'market', label: 'Luminária com base (mercado)', value: 2900, rationale: 'Luminárias com base LED: típico $26–$40.' },
      { id: 'high', label: 'Alto', value: 3900, rationale: 'Topo das luminárias ($39.99). Só com base/moldura premium.' },
    ],
    'market',
    [
      { label: 'Lithophane lamp', value: '$27.99', sourceUrl: `${ETSY}/market/3d_printed_lithophane_lamp` },
      { label: 'Lamp (outro vendedor)', value: '$39.99+', sourceUrl: `${ETSY}/listing/4489869742` },
      { label: 'Night lights de tomada', value: '$7.87–$15', sourceUrl: `${ETSY}/listing/1249787598` },
      { label: 'Base LED: custo NÃO pesquisado', value: 'somar ao custo', sourceUrl: `${ETSY}/market/color_lithophane_3d_print` },
    ],
  ),
  price(
    'thanksgiving-place-cards',
    'Personalized Place Card Holders',
    'conjunto de 6',
    48,
    [
      { id: 'low', label: 'Abaixo', value: 1500, rationale: '$2.50 por peça — perto dos personalizados avulsos ($1.05–$2.25).' },
      { id: 'market', label: 'Preço de mercado', value: 1800, rationale: 'Conjunto de 6 observado a $17.95; nosso é personalizado com nome.' },
      { id: 'high', label: 'Alto', value: 2400, rationale: '$4 por peça. Acima do observado.' },
    ],
    'market',
    [
      { label: 'Turkey place card holders (6)', value: '$17.95', sourceUrl: `${ETSY}/market/placecard_holders_bulk` },
      { label: 'Place card 3D personalizada (cada)', value: '$1.69–$2.25', sourceUrl: `${ETSY}/listing/4399124583` },
      { label: 'TinkerMake 3D (sem nome)', value: '$10 (2) a $38 (20)', sourceUrl: 'https://tinkermake.com/product/thanksgiving-pilgrim-hat-owl-place-card-holder-set' },
    ],
  ),
  price(
    'thanksgiving-napkin-rings',
    'Name Napkin Rings',
    'conjunto de 6',
    36,
    [
      { id: 'low', label: 'Preço por anel do mercado', value: 1500, rationale: '6 × ~$2.54 (anel 3D personalizado observado).' },
      { id: 'market', label: 'Recomendado', value: 1900, rationale: 'Um pouco acima do preço por anel, por ser conjunto personalizado pronto.' },
      { id: 'high', label: 'Alto', value: 2900, rationale: 'Entre 3D ($15) e conjuntos de outros materiais ($48).' },
    ],
    'market',
    [
      { label: 'Anel 3D personalizado (cada)', value: '$2.54', sourceUrl: `${ETSY}/listing/4537753035/personalized-3d-printed-napkin-rings` },
      { label: 'Set of 6 family napkin rings (material n/d)', value: '$48.00', sourceUrl: `${ETSY}/market/personalized_napkin_rings` },
      { label: 'Poucos dados de conjuntos 3D', value: 'amostra pequena', sourceUrl: `${ETSY}/market/3d_printed_napkin_ring_with_name` },
    ],
  ),
  price(
    'christmas-name-ornament',
    'Personalized Name Ornament',
    'cada',
    12,
    [
      { id: 'low', label: 'Abaixo', value: 900, rationale: 'Base do típico ($9). Bom para volume.' },
      { id: 'market', label: 'Preço de mercado', value: 1200, rationale: 'Típico observado $9–$13.' },
      { id: 'high', label: 'Multicor em camadas', value: 1600, rationale: 'Perto do topo ($17.84–$19.19).' },
    ],
    'market',
    [
      { label: 'Name ornament 3D', value: '$9.00', sourceUrl: `${ETSY}/market/3d_printer_name_christmas_ornament` },
      { label: 'Name ornament 3D', value: '$12.99', sourceUrl: `${ETSY}/market/christmas_ornament_3d_printed_name` },
      { label: 'Topo: name snowflake', value: '$19.19', sourceUrl: `${ETSY}/market/3d_printed_ornaments_personalized` },
      { label: 'Mínimo (promoção)', value: '$3.75', sourceUrl: `${ETSY}/market/3d_printed_snowflake_name_ornament` },
    ],
  ),
  price(
    'christmas-stocking-tags',
    'Stocking Name Tags',
    'conjunto de 4',
    32,
    [
      { id: 'low', label: '$4 por tag', value: 1600, rationale: 'Entre mini ($2.25) e padrão ($4.50).' },
      { id: 'market', label: '~$5.50 por tag', value: 2200, rationale: 'Mercado cobra ~$6 por tag; conjunto com leve desconto.' },
      { id: 'high', label: '$7 por tag', value: 2800, rationale: 'Preço anterior. Acima do típico.' },
    ],
    'market',
    [
      { label: 'Stocking tag mini / padrão', value: '$2.25 / $4.50', sourceUrl: `${ETSY}/listing/1615532123` },
      { label: 'Stocking tag', value: '$5.99', sourceUrl: `${ETSY}/listing/1821490900` },
      { label: 'Stocking tag', value: '$8.49', sourceUrl: `${ETSY}/listing/1839238869` },
      { label: 'Topo', value: '$11.99', sourceUrl: `${ETSY}/listing/1801739689` },
    ],
  ),
  price(
    'christmas-photo-lithophane',
    'Photo Lithophane Ornament',
    'cada',
    20,
    [
      { id: 'low', label: 'Abaixo', value: 1500, rationale: 'Base do típico ($15.30).' },
      { id: 'market', label: 'Com LED (mercado)', value: 1800, rationale: 'Típico $15–$18; listagem de $18 inclui 2 LEDs e gancho.' },
      { id: 'high', label: 'Premium', value: 2500, rationale: 'Faixa alta ($24.99–$29.99).' },
    ],
    'market',
    [
      { label: 'Sphere lithophane ornament', value: '$15.30', sourceUrl: `${ETSY}/listing/1607015121` },
      { label: 'Com 2 LEDs + gancho', value: '$18.00', sourceUrl: `${ETSY}/listing/4408778186` },
      { label: 'Faixa alta', value: '$24.99–$29.99', sourceUrl: `${ETSY}/market/lithophane_christmas_ornaments` },
    ],
  ),
  price(
    'pet-memorial',
    'Pet Memorial Keepsake (lithophane)',
    'cada',
    60,
    [
      { id: 'low', label: 'Abaixo', value: 1900, rationale: 'Perto de $19.99 observado.' },
      { id: 'market', label: 'Preço de mercado', value: 2400, rationale: 'Típico $20–$24 (night light $24).' },
      { id: 'high', label: 'Com LED e moldura', value: 3500, rationale: 'Versões coloridas com LED e moldura chegam a $44.99.' },
    ],
    'market',
    [
      { label: 'Lithophane portrait', value: '$19.99', sourceUrl: `${ETSY}/market/lithophane_portrait?page=3` },
      { label: 'Memorial night light', value: '$24.00', sourceUrl: `${ETSY}/listing/4460162520` },
      { label: 'Memorial keepsake', value: '$25.99', sourceUrl: `${ETSY}/market/lithophane_3d_print` },
      { label: 'Colorido com LED e moldura', value: '$44.99', sourceUrl: `${ETSY}/market/color_lithophane_3d_print` },
    ],
  ),
  price(
    'cake-topper',
    'Custom Cake Topper',
    'cada',
    15,
    [
      { id: 'low', label: 'Abaixo', value: 1000, rationale: 'Base do típico PLA ($10).' },
      { id: 'market', label: 'Preço de mercado', value: 1400, rationale: 'Típico PLA $10–$17.' },
      { id: 'high', label: 'Alto', value: 1900, rationale: 'Perto do topo de acrílico ($19.99).' },
    ],
    'market',
    [
      { label: 'Cake topper 3D PLA', value: '$13.50 / $15.98', sourceUrl: `${ETSY}/market/custom_3d_printed_cake_topper` },
      { label: 'Cake topper 3D PLA', value: '$15.09 / $17.16', sourceUrl: `${ETSY}/listing/1877031133` },
      { label: 'Acrílico (comparação)', value: '$6.99–$30', sourceUrl: `${ETSY}/market/acrylic_name_cake_topper` },
    ],
  ),
  price(
    'business-review-stand',
    'Google Review NFC + QR Stand (com logo)',
    'cada',
    60,
    [
      { id: 'low', label: 'Igual Amazon', value: 1900, rationale: 'Amazon/Etsy com logo: ~$15–$20.' },
      { id: 'market', label: 'Recomendado', value: 2500, rationale: 'Logo + NFC programado para a página de review. Abaixo das placas premium ($29.99+).' },
      { id: 'high', label: 'Premium', value: 3500, rationale: 'Faixa premium ($29.99–$79.92). Só com acabamento especial.' },
    ],
    'market',
    [
      { label: 'Custom logo tap stand (frete grátis)', value: '$19.99', sourceUrl: `${ETSY}/market/custom_nfc_tap_stand` },
      { label: 'Amazon (QRLynk, Amazon’s Choice)', value: '$16.99', sourceUrl: 'https://www.amazon.com/Review-Stand-Compatible-Google-Social/dp/B0F626T62X' },
      { label: 'ZappyCards stand', value: '$40 (1) · $25 (5+)', sourceUrl: 'https://zappycards.com/products/nfc-google-review-stand' },
      { label: 'NFC NTAG213 (100 un.)', value: '~$0.16/un.', sourceUrl: 'https://www.walmart.com/c/kp/nfc-stickers' },
    ],
    16,
    'NFC $0.16',
  ),
  price(
    'halloween-bat-wall-set',
    `Flying Bat Wall Set`,
    'conjunto de 12',
    40,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos conjuntos de 5–10 impressos ($10–$12).` },
      { id: 'market', label: `Preço de mercado`, value: 1800, rationale: `Conjuntos 3D de 5–10 peças ficam em $12–$20; 12 peças em 3 tamanhos.` },
      { id: 'high', label: `Alto`, value: 2400, rationale: `Topo observado ($20–$27, conjunto de 5 grande).` },
    ],
    'market',
    [
      { label: `Conjunto de 5 mini (3D)`, value: `$9.99`, sourceUrl: 'https://www.etsy.com/listing/4376787441' },
      { label: `Pack de 5 ou 10 (3D)`, value: `$11.76+`, sourceUrl: 'https://www.etsy.com/listing/4362952899' },
      { label: `Conjunto de 5, PLA`, value: `$20.03–$26.70`, sourceUrl: 'https://www.etsy.com/listing/4385702011' },
      { label: `Conjunto de 12 (material não informado)`, value: `$11`, sourceUrl: 'https://www.etsy.com/listing/1810106759' },
    ],
  ),
  price(
    'halloween-skull-planter',
    `Geometric Skull Planter`,
    'cada',
    70,
    [
      { id: 'low', label: `Abaixo`, value: 1100, rationale: `Base do típico ($11).` },
      { id: 'market', label: `Preço de mercado`, value: 1400, rationale: `Típico $11–$14.` },
      { id: 'high', label: `Alto`, value: 1900, rationale: `Perto do topo ($21–$22).` },
    ],
    'market',
    [
      { label: `Mini skull planter`, value: `$7.50`, sourceUrl: 'https://www.etsy.com/listing/1163849852' },
      { label: `Geometric skull mini`, value: `$11.00`, sourceUrl: 'https://www.etsy.com/listing/1165834715' },
      { label: `Skull planter`, value: `$13.99`, sourceUrl: 'https://www.etsy.com/listing/1549592952' },
      { label: `Com dreno (Walmart)`, value: `$21.41`, sourceUrl: 'https://www.walmart.com/ip/18679861959' },
    ],
  ),
  price(
    'halloween-pumpkin-lantern',
    `Pumpkin Glow Lantern`,
    'cada (LED incluso)',
    60,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos $15.99 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 1800, rationale: `Típico $8–$16 sem LED de qualidade; o nosso inclui LED.` },
      { id: 'high', label: `Alto`, value: 2600, rationale: `Versões grandes com luz chegam a $44.50.` },
    ],
    'market',
    [
      { label: `Jack-o-lantern tealight holder`, value: `$6.99`, sourceUrl: 'https://www.etsy.com/market/3d_printed_tea_light_pumpkin' },
      { label: `Light-up pumpkin com LED`, value: `$7.64`, sourceUrl: 'https://www.etsy.com/listing/4533414507' },
      { label: `Tea light holder`, value: `$15.99`, sourceUrl: 'https://www.etsy.com/listing/4320907226' },
      { label: `Grande com LED puck`, value: `$44.50`, sourceUrl: 'https://www.etsy.com/listing/4379125035' },
    ],
    80,
    'LED ~$0.80 (estimativa, não pesquisado)',
  ),
  price(
    'thanksgiving-pumpkin-trio',
    `Pumpkin Tealight Trio`,
    'conjunto de 3 (LED incluso)',
    120,
    [
      { id: 'low', label: `Abaixo`, value: 1500, rationale: `Conjuntos de 3 sem luz: $11–$12.` },
      { id: 'market', label: `Recomendado`, value: 1900, rationale: `Conjunto de 3 + 3 LEDs; 1 abóbora com LED sai $11.24.` },
      { id: 'high', label: `Alto`, value: 2600, rationale: `Faixa alta ($34 conjunto branco).` },
    ],
    'market',
    [
      { label: `Conjunto de 3`, value: `$12.00`, sourceUrl: 'https://www.etsy.com/listing/4383028259' },
      { label: `Conjunto de 3, sem luz`, value: `$11.08`, sourceUrl: 'https://www.etsy.com/listing/4344555999' },
      { label: `1 abóbora com LED`, value: `$11.24+`, sourceUrl: 'https://www.etsy.com/listing/4373630641' },
      { label: `Conjunto branco`, value: `$34.17`, sourceUrl: 'https://www.etsy.com/listing/4372639325' },
    ],
    240,
    '3 LEDs ~$2.40 (estimativa, não pesquisado)',
  ),
  price(
    'thanksgiving-leaf-garland',
    `Autumn Leaf Garland`,
    'cada',
    60,
    [
      { id: 'low', label: `Abaixo`, value: 1800, rationale: `Perto das placas 3D de Thanksgiving ($16).` },
      { id: 'market', label: `Recomendado`, value: 2400, rationale: `Sem garland 3D no mercado: referência = placas/decoração 3D ($16–$26).` },
      { id: 'high', label: `Alto`, value: 3200, rationale: `Acima do observado; só na versão 6 ft.` },
    ],
    'market',
    [
      { label: `Placa 3D "Happy Thanksgiving" (referência)`, value: `$16.26`, sourceUrl: 'https://www.etsy.com/market/3d_thanksgiving_sign' },
      { label: `Conjunto de decoração (referência)`, value: `$19.21`, sourceUrl: 'https://www.etsy.com/market/3d_thanksgiving_sign' },
      { label: `Placa "Thankful" (referência)`, value: `$25.99`, sourceUrl: 'https://www.etsy.com/market/thankful_table_sign' },
      { label: `Garland impressa em 3D`, value: `sem dados — produto novo`, sourceUrl: 'https://www.etsy.com/market/3d_thanksgiving_sign' },
    ],
  ),
  price(
    'christmas-snowflake-set',
    `Geometric Snowflake Set`,
    'conjunto de 6',
    48,
    [
      { id: 'low', label: `Abaixo`, value: 1800, rationale: `Entre o conjunto de 10 ($15.36) e o de 6 ($21).` },
      { id: 'market', label: `Preço de mercado`, value: 2200, rationale: `Conjunto de 6 observado a $21.25 (orig. $25).` },
      { id: 'high', label: `Alto`, value: 2800, rationale: `Acima do observado.` },
    ],
    'market',
    [
      { label: `Conjunto de 6`, value: `$21.25 (orig. $25)`, sourceUrl: 'https://www.etsy.com/listing/740844594' },
      { label: `Conjunto de 10`, value: `$15.36+`, sourceUrl: 'https://www.etsy.com/listing/4404146212' },
      { label: `1 floco (Canadá)`, value: `CA$11.74`, sourceUrl: 'https://www.etsy.com/ca/listing/4348530619' },
    ],
  ),
  price(
    'christmas-village-lantern',
    `Village House Lantern`,
    'cada (LED incluso)',
    110,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos $11.69 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 1800, rationale: `Típico $12–$16; topo $17 com LED.` },
      { id: 'high', label: `Alto`, value: 2400, rationale: `Acima do observado.` },
    ],
    'market',
    [
      { label: `Tealight house`, value: `$9.03`, sourceUrl: 'https://www.etsy.com/market/3d_printed_christmas_village' },
      { label: `Candle houses`, value: `$11.69`, sourceUrl: 'https://www.etsy.com/market/3d_printed_christmas_village' },
      { label: `Conjunto de 3 com LED`, value: `$15.99`, sourceUrl: 'https://www.etsy.com/market/tealight_christmas_village' },
      { label: `Gingerbread com LED`, value: `$17.14`, sourceUrl: 'https://www.etsy.com/market/gingerbread_house_tealight' },
    ],
    80,
    'LED ~$0.80 (estimativa, não pesquisado)',
  ),
  price(
    'christmas-star-topper',
    `Faceted Star Tree Topper`,
    'cada',
    60,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos $12–$15 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 1900, rationale: `Típico $12–$22.` },
      { id: 'high', label: `Alto`, value: 2500, rationale: `Topo observado ($24.99, silk PLA).` },
    ],
    'market',
    [
      { label: `Wish star`, value: `$5.00+`, sourceUrl: 'https://www.etsy.com/listing/1613146615' },
      { label: `8-bit star`, value: `$15.00`, sourceUrl: 'https://www.etsy.com/listing/1825898860' },
      { label: `Star topper silk PLA 7 in`, value: `$24.99`, sourceUrl: 'https://www.etsy.com/listing/1561406354' },
    ],
  ),
  price(
    'christmas-gift-tags',
    `Name Gift Tags`,
    'conjunto de 10',
    50,
    [
      { id: 'low', label: `Abaixo`, value: 2500, rationale: `$2.50 por etiqueta.` },
      { id: 'market', label: `Recomendado`, value: 3500, rationale: `Mercado cobra $4–$5 por etiqueta avulsa; conjunto com desconto ($3.50/un.).` },
      { id: 'high', label: `Alto`, value: 4500, rationale: `$4.50 por etiqueta, sem desconto.` },
    ],
    'market',
    [
      { label: `1 etiqueta com nome`, value: `$3.25+`, sourceUrl: 'https://www.etsy.com/listing/4389074178' },
      { label: `Etiqueta`, value: `$4.08–$5.00`, sourceUrl: 'https://www.etsy.com/market/3d_printed_stocking_name_tags' },
      { label: `Santa gift tag`, value: `$7.50`, sourceUrl: 'https://www.etsy.com/listing/1799805892' },
    ],
  ),
  price(
    'christmas-baby-first',
    `Baby's First Christmas Ornament`,
    'cada',
    15,
    [
      { id: 'low', label: `Abaixo`, value: 1000, rationale: `Impressos em 3D confirmados: $6–$8.` },
      { id: 'market', label: `Recomendado`, value: 1400, rationale: `Entre os impressos 3D ($6–$8) e os "3D" típicos ($13–$18).` },
      { id: 'high', label: `Alto`, value: 1800, rationale: `Faixa típica dos anúncios "3D" ($17.84).` },
    ],
    'market',
    [
      { label: `3D printed multicolor`, value: `$6.00`, sourceUrl: 'https://www.etsy.com/listing/1636752497' },
      { label: `Footprint keepsake 3D`, value: `$8.34`, sourceUrl: 'https://www.etsy.com/listing/4362249512' },
      { label: `Custom baby ornament`, value: `$12.99`, sourceUrl: 'https://www.etsy.com/listing/4392116982' },
      { label: `"3D relief" (provável UV)`, value: `$17.84`, sourceUrl: 'https://www.etsy.com/market/3d_baby_first_christmas_ornament' },
    ],
  ),
  price(
    'christmas-countdown',
    `Christmas Countdown Blocks`,
    'cada',
    120,
    [
      { id: 'low', label: `Abaixo`, value: 1800, rationale: `Perto dos $15 observados.` },
      { id: 'market', label: `Recomendado`, value: 2600, rationale: `Típico $15–$37; o nosso é personalizável.` },
      { id: 'high', label: `Alto`, value: 3500, rationale: `Perto do quadro flip-tile ($29.98) e chaminé ($36.95).` },
    ],
    'market',
    [
      { label: `Rotating countdown 25 dias`, value: `$15.00`, sourceUrl: 'https://www.etsy.com/listing/1817402960' },
      { label: `Flip-tile countdown 3D`, value: `$29.98`, sourceUrl: 'https://www.etsy.com/market/3d_printed_christmas_countdown' },
      { label: `Countdown com meias de nome`, value: `$36.95`, sourceUrl: 'https://www.etsy.com/market/3d_printed_christmas_countdown' },
    ],
  ),
  price(
    'moon-lamp',
    `Moon Lithophane Lamp`,
    'cada (LED + base)',
    90,
    [
      { id: 'low', label: `Abaixo`, value: 2900, rationale: `Perto dos $29.40 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 3500, rationale: `Típico $30–$41.` },
      { id: 'high', label: `Alto`, value: 4200, rationale: `Topo observado ($41–$42).` },
    ],
    'market',
    [
      { label: `Photo moon lithophane com LED USB-C`, value: `$25.95`, sourceUrl: 'https://odellcreations.com/products/globe-sphere-custom-photo-lithophane' },
      { label: `Moon lithophane com LED`, value: `$31.99`, sourceUrl: 'https://www.etsy.com/listing/809742816' },
      { label: `Moon lamp NASA`, value: `$41.10`, sourceUrl: 'https://www.etsy.com/listing/1827148702' },
    ],
    500,
    'base + LED ~$5 (estimativa, não pesquisado)',
  ),
  price(
    'geometric-planter',
    `Faceted Planter + Tray`,
    'cada',
    110,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos $12.71–$14.40 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 1800, rationale: `Típico $14–$21.` },
      { id: 'high', label: `Alto`, value: 2400, rationale: `Topo observado ($24.95).` },
    ],
    'market',
    [
      { label: `Com bandeja de drenagem`, value: `$13.56`, sourceUrl: 'https://www.etsy.com/market/3d_printed_pot_with_drainage' },
      { label: `Geométrico com pratinho`, value: `$14.40`, sourceUrl: 'https://www.etsy.com/listing/1130887547' },
      { label: `Self-draining com pratinho`, value: `$24.95`, sourceUrl: 'https://www.etsy.com/listing/4324227167' },
    ],
  ),
  price(
    'name-keychains',
    `Name Keychains`,
    'conjunto de 3',
    24,
    [
      { id: 'low', label: `Abaixo`, value: 800, rationale: `~$2.67 por chaveiro.` },
      { id: 'market', label: `Preço de mercado`, value: 1000, rationale: `Mercado $3–$3.50 por peça; conjunto de 3 com leve desconto.` },
      { id: 'high', label: `Alto`, value: 1400, rationale: `$4.67 por peça (topo).` },
    ],
    'market',
    [
      { label: `1 chaveiro com nome`, value: `$2.93`, sourceUrl: 'https://www.etsy.com/listing/1679743197' },
      { label: `1 chaveiro, até 14 letras`, value: `$3.45`, sourceUrl: 'https://www.etsy.com/listing/1704614337' },
      { label: `1 chaveiro, desconto em lote`, value: `$4.67`, sourceUrl: 'https://www.etsy.com/market/3d_printed_keychains_bulk' },
    ],
  ),
  price(
    'phone-stand',
    `Personalized Phone Stand`,
    'cada',
    60,
    [
      { id: 'low', label: `Abaixo`, value: 1500, rationale: `Perto dos $15.99 observados.` },
      { id: 'market', label: `Preço de mercado`, value: 1900, rationale: `Típico $16–$20.` },
      { id: 'high', label: `Alto`, value: 2500, rationale: `Acima do típico; temáticos chegam a $34.` },
    ],
    'market',
    [
      { label: `Custom text`, value: `$15.99`, sourceUrl: 'https://www.etsy.com/market/personalized_phone_stand_for_her' },
      { label: `Name phone stand`, value: `$19.99`, sourceUrl: 'https://www.etsy.com/listing/4475589915' },
      { label: `Temático com nome`, value: `$34.15`, sourceUrl: 'https://www.etsy.com/listing/4314469864' },
    ],
  ),
  price(
    'desk-nameplate',
    `Desk Nameplate`,
    'cada',
    80,
    [
      { id: 'low', label: `Abaixo`, value: 1400, rationale: `Perto dos $12.59 observados.` },
      { id: 'market', label: `Recomendado`, value: 1900, rationale: `Típico $10–$16; bicolor com título vale mais.` },
      { id: 'high', label: `Alto`, value: 2800, rationale: `Placas com título chegam a $28.98.` },
    ],
    'market',
    [
      { label: `Curved name plate`, value: `$9.24`, sourceUrl: 'https://www.etsy.com/listing/1365869868' },
      { label: `Desk sign`, value: `$12.59`, sourceUrl: 'https://www.etsy.com/listing/1645981846' },
      { label: `Teacher name plate com título`, value: `$28.98`, sourceUrl: 'https://www.etsy.com/listing/4335318451' },
    ],
  ),
  price(
    'soccer-jersey-keychain',
    `Soccer Jersey Keychain`,
    'cada',
    8,
    [
      { id: 'low', label: `Abaixo`, value: 400, rationale: `Abaixo do típico ($4.80–$5.35).` },
      { id: 'market', label: `Recomendado`, value: 600, rationale: `Um pouco acima do típico; nome + número + 2 cores (troca de filamento).` },
      { id: 'high', label: `Alto`, value: 800, rationale: `Topo observado ($7.99).` },
    ],
    'market',
    [
      { label: `Camisa com nome e número (~6 cm)`, value: `$5.35`, sourceUrl: 'https://www.etsy.com/listing/4487596194' },
      { label: `Camisa, nome até 10 letras`, value: `$4.79`, sourceUrl: 'https://www.etsy.com/listing/1872505460' },
      { label: `Camisa com cores do time (fidget)`, value: `$7.99`, sourceUrl: 'https://www.etsy.com/listing/4527382703' },
    ],
  ),
  price(
    'soccer-ball-keychain',
    `Soccer Ball Name Keychain`,
    'cada',
    10,
    [
      { id: 'low', label: `Abaixo`, value: 500, rationale: `Perto do mínimo observado ($4.25–$5.49).` },
      { id: 'market', label: `Preço de mercado`, value: 700, rationale: `Típico $5.50–$7.00.` },
      { id: 'high', label: `Alto`, value: 900, rationale: `Acima do topo observado ($7.99).` },
    ],
    'market',
    [
      { label: `Bola com nome (promoção)`, value: `$4.25`, sourceUrl: 'https://www.etsy.com/listing/4506487779' },
      { label: `Bag tag bola com nome e número`, value: `$5.49`, sourceUrl: 'https://www.etsy.com/listing/4395229215' },
      { label: `Bola, cor e fonte à escolha`, value: `$7.00`, sourceUrl: 'https://www.etsy.com/listing/1267238739' },
    ],
  ),
  price(
    'couple-heart-keychains',
    `Couple Heart Keychains`,
    'par (2 chaveiros)',
    12,
    [
      { id: 'low', label: `Abaixo`, value: 1000, rationale: `Entre o par sem nome ($6.50–$8) e o com nome.` },
      { id: 'market', label: `Preço de mercado`, value: 1500, rationale: `Pares com nomes: $14.35–$15.` },
      { id: 'high', label: `Alto`, value: 1900, rationale: `Preço original antes de promoção ($19.14).` },
    ],
    'market',
    [
      { label: `Par sem nomes, PLA`, value: `$6.51`, sourceUrl: 'https://www.etsy.com/listing/569314720' },
      { label: `Par com nomes, 3D (orig. $19.14)`, value: `$14.35`, sourceUrl: 'https://www.etsy.com/listing/4477372479' },
      { label: `Split heart com nomes`, value: `$15.00`, sourceUrl: 'https://www.etsy.com/listing/1393455778' },
    ],
  ),
  price(
    'kids-name-sign',
    `Kids Room Name Sign`,
    'cada',
    60,
    [
      { id: 'low', label: `Abaixo`, value: 1600, rationale: `Abaixo do típico ($17.60–$21).` },
      { id: 'market', label: `Preço de mercado`, value: 2200, rationale: `Típico $17.60–$21 para placa em pé (dado fraco: muitos cobram por letra).` },
      { id: 'high', label: `Alto`, value: 3000, rationale: `Perto do topo observado ($32, letras em camadas).` },
    ],
    'market',
    [
      { label: `Placa de nome com base`, value: `$17.60+`, sourceUrl: 'https://www.etsy.com/listing/904875868' },
      { label: `Placa em pé para quarto infantil`, value: `$20.96`, sourceUrl: 'https://www.etsy.com/listing/1892420308' },
      { label: `Letras em camadas, PLA`, value: `$32.00`, sourceUrl: 'https://www.etsy.com/market/3d_printed_freestanding_letters' },
    ],
  ),
  price(
    'business-card-holder',
    `Logo Business Card Holder`,
    'cada',
    50,
    [
      { id: 'low', label: `Abaixo`, value: 1500, rationale: `Perto dos $11–$12 personalizados só com nome.` },
      { id: 'market', label: `Recomendado`, value: 1900, rationale: `Topo padrão observado ($18.99); logo exige trabalho extra.` },
      { id: 'high', label: `Alto`, value: 2500, rationale: `Logo totalmente customizado (mercado cobra à parte).` },
    ],
    'market',
    [
      { label: `Com nome, bicolor`, value: `$9.35`, sourceUrl: 'https://www.etsy.com/listing/865659584' },
      { label: `Personalizado 90×50 mm`, value: `$11.08`, sourceUrl: 'https://www.etsy.com/listing/1862373097' },
      { label: `Padrão (custom total é mais caro)`, value: `$18.99`, sourceUrl: 'https://www.etsy.com/listing/4496237338' },
    ],
  ),
  price(
    'business-table-numbers',
    `Table Number Set`,
    'conjunto de 10',
    200,
    [
      { id: 'low', label: `Abaixo`, value: 5000, rationale: `$5 por número.` },
      { id: 'market', label: `Preço de mercado`, value: 6500, rationale: `$6.50 por número; mercado $5–$9.` },
      { id: 'high', label: `Alto`, value: 8500, rationale: `$8.50 por número (topo).` },
    ],
    'market',
    [
      { label: `1 número PLA`, value: `$4.45`, sourceUrl: 'https://www.etsy.com/listing/4447803569' },
      { label: `1 número 4 in`, value: `$6.00`, sourceUrl: 'https://www.etsy.com/listing/1429898984' },
      { label: `1 número serifado`, value: `$8.99`, sourceUrl: 'https://www.etsy.com/listing/4409844485' },
    ],
  ),
  price(
    'business-logo-keychains',
    `Logo Keychains (bulk)`,
    'pacote de 50',
    400,
    [
      { id: 'low', label: `Abaixo`, value: 17500, rationale: `$3.50 por peça.` },
      { id: 'market', label: `Preço de mercado`, value: 22500, rationale: `$4.50 por peça em 50–99 (única tabela clara, loja do Canadá).` },
      { id: 'high', label: `Alto`, value: 27500, rationale: `$5.50 por peça.` },
    ],
    'market',
    [
      { label: `Tabela 25/50/100 (Canadá, CAD provável)`, value: `$6.00 / $4.50 / $3.75`, sourceUrl: 'https://gm3dprint.com/products/custom-logo-keychains-bulk-orders' },
      { label: `Logo keychain por peça`, value: `$5.99`, sourceUrl: 'https://www.etsy.com/market/small_business_3d_printed_items' },
      { label: `Comparação: PVC 100 un.`, value: `$175–$258`, sourceUrl: 'https://www.etsy.com/listing/1729031970' },
    ],
    2500,
    '50 argolas ~$25 (estimativa, não pesquisado)',
  ),
];
